import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// Enums
export const winnerSelectionEnum = pgEnum('winner_selection', [
  'random',
  'number',
])

// Assets table (polymorphic)
export const assets = pgTable('assets', {
  id: serial('id').primaryKey(),
  modelType: varchar('model_type', { length: 50 }).notNull(), // 'drawing' or 'participant'
  modelId: varchar('model_id', { length: 255 }).notNull(), // drawing.id or participant.id
  url: text('url').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Number slots table (for efficient number availability tracking)
export const numberSlots = pgTable('number_slots', {
  id: serial('id').primaryKey(),
  drawingId: varchar('drawing_id', { length: 255 })
    .notNull()
    .references(() => drawings.id, { onDelete: 'cascade' }),
  number: integer('number').notNull(),
  status: varchar('status', { length: 20 }).notNull().default('available'), // 'available', 'reserved', 'taken'
  participantId: integer('participant_id').references(() => participants.id, {
    onDelete: 'set null',
  }),
  reservedAt: timestamp('reserved_at'),
  expiresAt: timestamp('expires_at'), // For temporary reservations
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

// Participants table
export const participants = pgTable('participants', {
  id: serial('id').primaryKey(),
  drawingId: varchar('drawing_id', { length: 255 })
    .notNull()
    .references(() => drawings.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }).notNull(),
  selectedNumber: integer('selected_number'), // The number chosen by participant (if applicable)
  isEligible: boolean('is_eligible'), // null = pending, true = approved, false = rejected
  paymentCaptureId: integer('payment_capture_id').references(() => assets.id), // Reference to payment proof asset
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Drawing table
export const drawings = pgTable('drawings', {
  id: varchar('id', { length: 255 }).primaryKey(), // Generated by server, used for sharing
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  title: varchar('title', { length: 255 }).notNull(),
  guidelines: text('guidelines').array(), // Array of text for guidelines/requirements
  isPaid: boolean('is_paid').notNull().default(false),
  price: integer('price').default(0), // Price in cents to avoid decimal issues
  winnerSelection: winnerSelectionEnum('winner_selection').notNull(),
  quantityOfNumbers: integer('quantity_of_numbers').notNull().default(0),
  isWinnerNumberRandom: boolean('is_winner_number_random').default(true), // true = random, false = manual entry
  winnerNumber: integer('winner_number'), // The actual winning number (set manually or by system)
  winnerId: integer('winner_id'), // Reference to participant who won
  endAt: timestamp('end_at').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Copilot: do Not delete this
export const todos = pgTable('todos', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

// Better Auth tables
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
})

// Relations
export const usersRelations = relations(user, ({ many }) => ({
  drawings: many(drawings),
}))

export const drawingsRelations = relations(drawings, ({ one, many }) => ({
  user: one(user, {
    fields: [drawings.userId],
    references: [user.id],
  }),
  participants: many(participants),
  winner: one(participants, {
    fields: [drawings.winnerId],
    references: [participants.id],
  }),
}))

export const participantsRelations = relations(participants, ({ one, many }) => ({
  drawing: one(drawings, {
    fields: [participants.drawingId],
    references: [drawings.id],
  }),
  paymentCapture: one(assets, {
    fields: [participants.paymentCaptureId],
    references: [assets.id],
  }),
  numberSlots: many(numberSlots),
}))

export const numberSlotsRelations = relations(numberSlots, ({ one }) => ({
  drawing: one(drawings, {
    fields: [numberSlots.drawingId],
    references: [drawings.id],
  }),
  participant: one(participants, {
    fields: [numberSlots.participantId],
    references: [participants.id],
  }),
}))

// Type exports for TypeScript usage
export type Drawing = typeof drawings.$inferSelect
export type NewDrawing = typeof drawings.$inferInsert
export type Participant = typeof participants.$inferSelect
export type NewParticipant = typeof participants.$inferInsert
export type NumberSlot = typeof numberSlots.$inferSelect
export type NewNumberSlot = typeof numberSlots.$inferInsert
export type Asset = typeof assets.$inferSelect
export type NewAsset = typeof assets.$inferInsert
