/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoreRouteImport } from './routes/store'
import { Route as MercadopagoDemoRouteImport } from './routes/mercadopago-demo'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawingsIndexRouteImport } from './routes/drawings/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as DrawingsCreateRouteImport } from './routes/drawings/create'
import { Route as AuthenticationSignupRouteImport } from './routes/authentication/signup'
import { Route as AuthenticationResetPasswordRouteImport } from './routes/authentication/reset-password'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as AuthenticationForgotPasswordRouteImport } from './routes/authentication/forgot-password'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ACouponsRouteImport } from './routes/a/coupons'
import { Route as SlotDrawingIdIndexRouteImport } from './routes/slot/$drawingId/index'
import { Route as DrawingsDrawingIdIndexRouteImport } from './routes/drawings/$drawingId/index'
import { Route as ApiPacksIndexRouteImport } from './routes/api/packs/index'
import { Route as ApiDrawingsIndexRouteImport } from './routes/api/drawings/index'
import { Route as SlotDrawingIdNumberToReserveRouteImport } from './routes/slot/$drawingId/$numberToReserve'
import { Route as DrawingsDrawingIdEditRouteImport } from './routes/drawings/$drawingId/edit'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook.polar'
import { Route as ApiWebhookPaypalRouteImport } from './routes/api/webhook.paypal'
import { Route as ApiUserMonthlyAllowanceRouteImport } from './routes/api/user/monthly-allowance'
import { Route as ApiUserBalanceRouteImport } from './routes/api/user/balance'
import { Route as ApiPaypalCreateOrderRouteImport } from './routes/api/paypal/create-order'
import { Route as ApiPaypalCaptureOrderRouteImport } from './routes/api/paypal/capture-order'
import { Route as ApiParticipantsUploadRouteImport } from './routes/api/participants/upload'
import { Route as ApiParticipantsAssetsRouteImport } from './routes/api/participants/assets'
import { Route as ApiParticipantParticipantIdRouteImport } from './routes/api/participant.$participantId'
import { Route as ApiPacksPurchaseRouteImport } from './routes/api/packs/purchase'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api/mercadopago/webhook'
import { Route as ApiMercadopagoCreatePreferenceRouteImport } from './routes/api/mercadopago/create-preference'
import { Route as ApiDrawingsReservationTimeRouteImport } from './routes/api/drawings/reservation-time'
import { Route as ApiDrawingsDrawingIdRouteImport } from './routes/api/drawings/$drawingId'
import { Route as ApiCouponsRedeemRouteImport } from './routes/api/coupons/redeem'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdsRedeemRouteImport } from './routes/api/ads/redeem'
import { Route as ApiACouponsRouteImport } from './routes/api/a/coupons'
import { Route as DrawingsDrawingIdPParticipateIdRouteImport } from './routes/drawings/$drawingId/p.$participateId'
import { Route as DrawingsDrawingIdMParticipantRouteImport } from './routes/drawings/$drawingId/m.$participant'
import { Route as DDrawingIdPParticipantRouteImport } from './routes/d.$drawingId.p.$participant'
import { Route as ApiParticipantParticipantIdCommentsRouteImport } from './routes/api/participant/$participantId.comments'
import { Route as ApiDrawingsDrawingIdUploadRouteImport } from './routes/api/drawings/$drawingId/upload'
import { Route as ApiDrawingsDrawingIdStatsRouteImport } from './routes/api/drawings/$drawingId.stats'
import { Route as ApiDrawingsDrawingIdSlotsRouteImport } from './routes/api/drawings/$drawingId.slots'
import { Route as ApiDrawingsDrawingIdSelectWinnersRouteImport } from './routes/api/drawings/$drawingId.select-winners'
import { Route as ApiDrawingsDrawingIdReserveRouteImport } from './routes/api/drawings/$drawingId.reserve'
import { Route as ApiDrawingsDrawingIdParticipateRouteImport } from './routes/api/drawings/$drawingId/participate'
import { Route as ApiDrawingsDrawingIdParticipantsRouteImport } from './routes/api/drawings/$drawingId/participants'
import { Route as ApiDrawingsDrawingIdAssetsRouteImport } from './routes/api/drawings/$drawingId/assets'
import { Route as ApiDrawingsDrawingIdParticipantIdRouteImport } from './routes/api/drawings/$drawingId/$participantId'
import { Route as ApiDrawingsDrawingIdPParticipantIdCommentsRouteImport } from './routes/api/drawings/$drawingId/p/$participantId.comments'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadopagoDemoRoute = MercadopagoDemoRouteImport.update({
  id: '/mercadopago-demo',
  path: '/mercadopago-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/drawings/',
  path: '/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsCreateRoute = DrawingsCreateRouteImport.update({
  id: '/drawings/create',
  path: '/drawings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignupRoute = AuthenticationSignupRouteImport.update({
  id: '/authentication/signup',
  path: '/authentication/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationResetPasswordRoute =
  AuthenticationResetPasswordRouteImport.update({
    id: '/authentication/reset-password',
    path: '/authentication/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationForgotPasswordRoute =
  AuthenticationForgotPasswordRouteImport.update({
    id: '/authentication/forgot-password',
    path: '/authentication/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ACouponsRoute = ACouponsRouteImport.update({
  id: '/a/coupons',
  path: '/a/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotDrawingIdIndexRoute = SlotDrawingIdIndexRouteImport.update({
  id: '/slot/$drawingId/',
  path: '/slot/$drawingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsDrawingIdIndexRoute = DrawingsDrawingIdIndexRouteImport.update({
  id: '/drawings/$drawingId/',
  path: '/drawings/$drawingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksIndexRoute = ApiPacksIndexRouteImport.update({
  id: '/api/packs/',
  path: '/api/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsIndexRoute = ApiDrawingsIndexRouteImport.update({
  id: '/api/drawings/',
  path: '/api/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotDrawingIdNumberToReserveRoute =
  SlotDrawingIdNumberToReserveRouteImport.update({
    id: '/slot/$drawingId/$numberToReserve',
    path: '/slot/$drawingId/$numberToReserve',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrawingsDrawingIdEditRoute = DrawingsDrawingIdEditRouteImport.update({
  id: '/drawings/$drawingId/edit',
  path: '/drawings/$drawingId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPaypalRoute = ApiWebhookPaypalRouteImport.update({
  id: '/api/webhook/paypal',
  path: '/api/webhook/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserMonthlyAllowanceRoute = ApiUserMonthlyAllowanceRouteImport.update({
  id: '/api/user/monthly-allowance',
  path: '/api/user/monthly-allowance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserBalanceRoute = ApiUserBalanceRouteImport.update({
  id: '/api/user/balance',
  path: '/api/user/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCreateOrderRoute = ApiPaypalCreateOrderRouteImport.update({
  id: '/api/paypal/create-order',
  path: '/api/paypal/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCaptureOrderRoute = ApiPaypalCaptureOrderRouteImport.update({
  id: '/api/paypal/capture-order',
  path: '/api/paypal/capture-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantsUploadRoute = ApiParticipantsUploadRouteImport.update({
  id: '/api/participants/upload',
  path: '/api/participants/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantsAssetsRoute = ApiParticipantsAssetsRouteImport.update({
  id: '/api/participants/assets',
  path: '/api/participants/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantParticipantIdRoute =
  ApiParticipantParticipantIdRouteImport.update({
    id: '/api/participant/$participantId',
    path: '/api/participant/$participantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPacksPurchaseRoute = ApiPacksPurchaseRouteImport.update({
  id: '/api/packs/purchase',
  path: '/api/packs/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadopagoCreatePreferenceRoute =
  ApiMercadopagoCreatePreferenceRouteImport.update({
    id: '/api/mercadopago/create-preference',
    path: '/api/mercadopago/create-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDrawingsReservationTimeRoute =
  ApiDrawingsReservationTimeRouteImport.update({
    id: '/api/drawings/reservation-time',
    path: '/api/drawings/reservation-time',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDrawingsDrawingIdRoute = ApiDrawingsDrawingIdRouteImport.update({
  id: '/api/drawings/$drawingId',
  path: '/api/drawings/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsRedeemRoute = ApiCouponsRedeemRouteImport.update({
  id: '/api/coupons/redeem',
  path: '/api/coupons/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRedeemRoute = ApiAdsRedeemRouteImport.update({
  id: '/api/ads/redeem',
  path: '/api/ads/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiACouponsRoute = ApiACouponsRouteImport.update({
  id: '/api/a/coupons',
  path: '/api/a/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsDrawingIdPParticipateIdRoute =
  DrawingsDrawingIdPParticipateIdRouteImport.update({
    id: '/drawings/$drawingId/p/$participateId',
    path: '/drawings/$drawingId/p/$participateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrawingsDrawingIdMParticipantRoute =
  DrawingsDrawingIdMParticipantRouteImport.update({
    id: '/drawings/$drawingId/m/$participant',
    path: '/drawings/$drawingId/m/$participant',
    getParentRoute: () => rootRouteImport,
  } as any)
const DDrawingIdPParticipantRoute = DDrawingIdPParticipantRouteImport.update({
  id: '/d/$drawingId/p/$participant',
  path: '/d/$drawingId/p/$participant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantParticipantIdCommentsRoute =
  ApiParticipantParticipantIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => ApiParticipantParticipantIdRoute,
  } as any)
const ApiDrawingsDrawingIdUploadRoute =
  ApiDrawingsDrawingIdUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdStatsRoute =
  ApiDrawingsDrawingIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdSlotsRoute =
  ApiDrawingsDrawingIdSlotsRouteImport.update({
    id: '/slots',
    path: '/slots',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdSelectWinnersRoute =
  ApiDrawingsDrawingIdSelectWinnersRouteImport.update({
    id: '/select-winners',
    path: '/select-winners',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdReserveRoute =
  ApiDrawingsDrawingIdReserveRouteImport.update({
    id: '/reserve',
    path: '/reserve',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipateRoute =
  ApiDrawingsDrawingIdParticipateRouteImport.update({
    id: '/participate',
    path: '/participate',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipantsRoute =
  ApiDrawingsDrawingIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdAssetsRoute =
  ApiDrawingsDrawingIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipantIdRoute =
  ApiDrawingsDrawingIdParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdPParticipantIdCommentsRoute =
  ApiDrawingsDrawingIdPParticipantIdCommentsRouteImport.update({
    id: '/p/$participantId/comments',
    path: '/p/$participantId/comments',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/mercadopago-demo': typeof MercadopagoDemoRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/reset-password': typeof AuthenticationResetPasswordRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account': typeof AccountIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/mercadopago/create-preference': typeof ApiMercadopagoCreatePreferenceRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRouteWithChildren
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/paypal/capture-order': typeof ApiPaypalCaptureOrderRoute
  '/api/paypal/create-order': typeof ApiPaypalCreateOrderRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/packs': typeof ApiPacksIndexRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/api/participant/$participantId/comments': typeof ApiParticipantParticipantIdCommentsRoute
  '/d/$drawingId/p/$participant': typeof DDrawingIdPParticipantRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/api/drawings/$drawingId/p/$participantId/comments': typeof ApiDrawingsDrawingIdPParticipantIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/mercadopago-demo': typeof MercadopagoDemoRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/reset-password': typeof AuthenticationResetPasswordRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account': typeof AccountIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/mercadopago/create-preference': typeof ApiMercadopagoCreatePreferenceRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRouteWithChildren
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/paypal/capture-order': typeof ApiPaypalCaptureOrderRoute
  '/api/paypal/create-order': typeof ApiPaypalCreateOrderRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/packs': typeof ApiPacksIndexRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/api/participant/$participantId/comments': typeof ApiParticipantParticipantIdCommentsRoute
  '/d/$drawingId/p/$participant': typeof DDrawingIdPParticipantRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/api/drawings/$drawingId/p/$participantId/comments': typeof ApiDrawingsDrawingIdPParticipantIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/mercadopago-demo': typeof MercadopagoDemoRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/reset-password': typeof AuthenticationResetPasswordRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account/': typeof AccountIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/mercadopago/create-preference': typeof ApiMercadopagoCreatePreferenceRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRouteWithChildren
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/paypal/capture-order': typeof ApiPaypalCaptureOrderRoute
  '/api/paypal/create-order': typeof ApiPaypalCreateOrderRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/drawings/': typeof ApiDrawingsIndexRoute
  '/api/packs/': typeof ApiPacksIndexRoute
  '/drawings/$drawingId/': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId/': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/api/participant/$participantId/comments': typeof ApiParticipantParticipantIdCommentsRoute
  '/d/$drawingId/p/$participant': typeof DDrawingIdPParticipantRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/api/drawings/$drawingId/p/$participantId/comments': typeof ApiDrawingsDrawingIdPParticipantIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coffee'
    | '/mercadopago-demo'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/forgot-password'
    | '/authentication/login'
    | '/authentication/reset-password'
    | '/authentication/signup'
    | '/drawings/create'
    | '/account'
    | '/authentication'
    | '/drawings'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/mercadopago/create-preference'
    | '/api/mercadopago/webhook'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/paypal/capture-order'
    | '/api/paypal/create-order'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/paypal'
    | '/api/webhook/polar'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/drawings'
    | '/api/packs'
    | '/drawings/$drawingId'
    | '/slot/$drawingId'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/api/participant/$participantId/comments'
    | '/d/$drawingId/p/$participant'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/api/drawings/$drawingId/p/$participantId/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coffee'
    | '/mercadopago-demo'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/forgot-password'
    | '/authentication/login'
    | '/authentication/reset-password'
    | '/authentication/signup'
    | '/drawings/create'
    | '/account'
    | '/authentication'
    | '/drawings'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/mercadopago/create-preference'
    | '/api/mercadopago/webhook'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/paypal/capture-order'
    | '/api/paypal/create-order'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/paypal'
    | '/api/webhook/polar'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/drawings'
    | '/api/packs'
    | '/drawings/$drawingId'
    | '/slot/$drawingId'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/api/participant/$participantId/comments'
    | '/d/$drawingId/p/$participant'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/api/drawings/$drawingId/p/$participantId/comments'
  id:
    | '__root__'
    | '/'
    | '/coffee'
    | '/mercadopago-demo'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/forgot-password'
    | '/authentication/login'
    | '/authentication/reset-password'
    | '/authentication/signup'
    | '/drawings/create'
    | '/account/'
    | '/authentication/'
    | '/drawings/'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/mercadopago/create-preference'
    | '/api/mercadopago/webhook'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/paypal/capture-order'
    | '/api/paypal/create-order'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/paypal'
    | '/api/webhook/polar'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/drawings/'
    | '/api/packs/'
    | '/drawings/$drawingId/'
    | '/slot/$drawingId/'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/api/participant/$participantId/comments'
    | '/d/$drawingId/p/$participant'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/api/drawings/$drawingId/p/$participantId/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoffeeRoute: typeof CoffeeRoute
  MercadopagoDemoRoute: typeof MercadopagoDemoRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  ACouponsRoute: typeof ACouponsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationResetPasswordRoute: typeof AuthenticationResetPasswordRoute
  AuthenticationSignupRoute: typeof AuthenticationSignupRoute
  DrawingsCreateRoute: typeof DrawingsCreateRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
  ApiACouponsRoute: typeof ApiACouponsRoute
  ApiAdsRedeemRoute: typeof ApiAdsRedeemRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCouponsRedeemRoute: typeof ApiCouponsRedeemRoute
  ApiDrawingsDrawingIdRoute: typeof ApiDrawingsDrawingIdRouteWithChildren
  ApiDrawingsReservationTimeRoute: typeof ApiDrawingsReservationTimeRoute
  ApiMercadopagoCreatePreferenceRoute: typeof ApiMercadopagoCreatePreferenceRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
  ApiPacksPurchaseRoute: typeof ApiPacksPurchaseRoute
  ApiParticipantParticipantIdRoute: typeof ApiParticipantParticipantIdRouteWithChildren
  ApiParticipantsAssetsRoute: typeof ApiParticipantsAssetsRoute
  ApiParticipantsUploadRoute: typeof ApiParticipantsUploadRoute
  ApiPaypalCaptureOrderRoute: typeof ApiPaypalCaptureOrderRoute
  ApiPaypalCreateOrderRoute: typeof ApiPaypalCreateOrderRoute
  ApiUserBalanceRoute: typeof ApiUserBalanceRoute
  ApiUserMonthlyAllowanceRoute: typeof ApiUserMonthlyAllowanceRoute
  ApiWebhookPaypalRoute: typeof ApiWebhookPaypalRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
  DrawingsDrawingIdEditRoute: typeof DrawingsDrawingIdEditRoute
  SlotDrawingIdNumberToReserveRoute: typeof SlotDrawingIdNumberToReserveRoute
  ApiDrawingsIndexRoute: typeof ApiDrawingsIndexRoute
  ApiPacksIndexRoute: typeof ApiPacksIndexRoute
  DrawingsDrawingIdIndexRoute: typeof DrawingsDrawingIdIndexRoute
  SlotDrawingIdIndexRoute: typeof SlotDrawingIdIndexRoute
  DDrawingIdPParticipantRoute: typeof DDrawingIdPParticipantRoute
  DrawingsDrawingIdMParticipantRoute: typeof DrawingsDrawingIdMParticipantRoute
  DrawingsDrawingIdPParticipateIdRoute: typeof DrawingsDrawingIdPParticipateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercadopago-demo': {
      id: '/mercadopago-demo'
      path: '/mercadopago-demo'
      fullPath: '/mercadopago-demo'
      preLoaderRoute: typeof MercadopagoDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/create': {
      id: '/drawings/create'
      path: '/drawings/create'
      fullPath: '/drawings/create'
      preLoaderRoute: typeof DrawingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/signup': {
      id: '/authentication/signup'
      path: '/authentication/signup'
      fullPath: '/authentication/signup'
      preLoaderRoute: typeof AuthenticationSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/reset-password': {
      id: '/authentication/reset-password'
      path: '/authentication/reset-password'
      fullPath: '/authentication/reset-password'
      preLoaderRoute: typeof AuthenticationResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot-password': {
      id: '/authentication/forgot-password'
      path: '/authentication/forgot-password'
      fullPath: '/authentication/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/coupons': {
      id: '/a/coupons'
      path: '/a/coupons'
      fullPath: '/a/coupons'
      preLoaderRoute: typeof ACouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$drawingId/': {
      id: '/slot/$drawingId/'
      path: '/slot/$drawingId'
      fullPath: '/slot/$drawingId'
      preLoaderRoute: typeof SlotDrawingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/': {
      id: '/drawings/$drawingId/'
      path: '/drawings/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof DrawingsDrawingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/': {
      id: '/api/packs/'
      path: '/api/packs'
      fullPath: '/api/packs'
      preLoaderRoute: typeof ApiPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/': {
      id: '/api/drawings/'
      path: '/api/drawings'
      fullPath: '/api/drawings'
      preLoaderRoute: typeof ApiDrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$drawingId/$numberToReserve': {
      id: '/slot/$drawingId/$numberToReserve'
      path: '/slot/$drawingId/$numberToReserve'
      fullPath: '/slot/$drawingId/$numberToReserve'
      preLoaderRoute: typeof SlotDrawingIdNumberToReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/edit': {
      id: '/drawings/$drawingId/edit'
      path: '/drawings/$drawingId/edit'
      fullPath: '/drawings/$drawingId/edit'
      preLoaderRoute: typeof DrawingsDrawingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/paypal': {
      id: '/api/webhook/paypal'
      path: '/api/webhook/paypal'
      fullPath: '/api/webhook/paypal'
      preLoaderRoute: typeof ApiWebhookPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/monthly-allowance': {
      id: '/api/user/monthly-allowance'
      path: '/api/user/monthly-allowance'
      fullPath: '/api/user/monthly-allowance'
      preLoaderRoute: typeof ApiUserMonthlyAllowanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/balance': {
      id: '/api/user/balance'
      path: '/api/user/balance'
      fullPath: '/api/user/balance'
      preLoaderRoute: typeof ApiUserBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/create-order': {
      id: '/api/paypal/create-order'
      path: '/api/paypal/create-order'
      fullPath: '/api/paypal/create-order'
      preLoaderRoute: typeof ApiPaypalCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/capture-order': {
      id: '/api/paypal/capture-order'
      path: '/api/paypal/capture-order'
      fullPath: '/api/paypal/capture-order'
      preLoaderRoute: typeof ApiPaypalCaptureOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participants/upload': {
      id: '/api/participants/upload'
      path: '/api/participants/upload'
      fullPath: '/api/participants/upload'
      preLoaderRoute: typeof ApiParticipantsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participants/assets': {
      id: '/api/participants/assets'
      path: '/api/participants/assets'
      fullPath: '/api/participants/assets'
      preLoaderRoute: typeof ApiParticipantsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participant/$participantId': {
      id: '/api/participant/$participantId'
      path: '/api/participant/$participantId'
      fullPath: '/api/participant/$participantId'
      preLoaderRoute: typeof ApiParticipantParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/purchase': {
      id: '/api/packs/purchase'
      path: '/api/packs/purchase'
      fullPath: '/api/packs/purchase'
      preLoaderRoute: typeof ApiPacksPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercadopago/create-preference': {
      id: '/api/mercadopago/create-preference'
      path: '/api/mercadopago/create-preference'
      fullPath: '/api/mercadopago/create-preference'
      preLoaderRoute: typeof ApiMercadopagoCreatePreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/reservation-time': {
      id: '/api/drawings/reservation-time'
      path: '/api/drawings/reservation-time'
      fullPath: '/api/drawings/reservation-time'
      preLoaderRoute: typeof ApiDrawingsReservationTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/$drawingId': {
      id: '/api/drawings/$drawingId'
      path: '/api/drawings/$drawingId'
      fullPath: '/api/drawings/$drawingId'
      preLoaderRoute: typeof ApiDrawingsDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/redeem': {
      id: '/api/coupons/redeem'
      path: '/api/coupons/redeem'
      fullPath: '/api/coupons/redeem'
      preLoaderRoute: typeof ApiCouponsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/redeem': {
      id: '/api/ads/redeem'
      path: '/api/ads/redeem'
      fullPath: '/api/ads/redeem'
      preLoaderRoute: typeof ApiAdsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a/coupons': {
      id: '/api/a/coupons'
      path: '/api/a/coupons'
      fullPath: '/api/a/coupons'
      preLoaderRoute: typeof ApiACouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/p/$participateId': {
      id: '/drawings/$drawingId/p/$participateId'
      path: '/drawings/$drawingId/p/$participateId'
      fullPath: '/drawings/$drawingId/p/$participateId'
      preLoaderRoute: typeof DrawingsDrawingIdPParticipateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/m/$participant': {
      id: '/drawings/$drawingId/m/$participant'
      path: '/drawings/$drawingId/m/$participant'
      fullPath: '/drawings/$drawingId/m/$participant'
      preLoaderRoute: typeof DrawingsDrawingIdMParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$drawingId/p/$participant': {
      id: '/d/$drawingId/p/$participant'
      path: '/d/$drawingId/p/$participant'
      fullPath: '/d/$drawingId/p/$participant'
      preLoaderRoute: typeof DDrawingIdPParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participant/$participantId/comments': {
      id: '/api/participant/$participantId/comments'
      path: '/comments'
      fullPath: '/api/participant/$participantId/comments'
      preLoaderRoute: typeof ApiParticipantParticipantIdCommentsRouteImport
      parentRoute: typeof ApiParticipantParticipantIdRoute
    }
    '/api/drawings/$drawingId/upload': {
      id: '/api/drawings/$drawingId/upload'
      path: '/upload'
      fullPath: '/api/drawings/$drawingId/upload'
      preLoaderRoute: typeof ApiDrawingsDrawingIdUploadRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/stats': {
      id: '/api/drawings/$drawingId/stats'
      path: '/stats'
      fullPath: '/api/drawings/$drawingId/stats'
      preLoaderRoute: typeof ApiDrawingsDrawingIdStatsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/slots': {
      id: '/api/drawings/$drawingId/slots'
      path: '/slots'
      fullPath: '/api/drawings/$drawingId/slots'
      preLoaderRoute: typeof ApiDrawingsDrawingIdSlotsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/select-winners': {
      id: '/api/drawings/$drawingId/select-winners'
      path: '/select-winners'
      fullPath: '/api/drawings/$drawingId/select-winners'
      preLoaderRoute: typeof ApiDrawingsDrawingIdSelectWinnersRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/reserve': {
      id: '/api/drawings/$drawingId/reserve'
      path: '/reserve'
      fullPath: '/api/drawings/$drawingId/reserve'
      preLoaderRoute: typeof ApiDrawingsDrawingIdReserveRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/participate': {
      id: '/api/drawings/$drawingId/participate'
      path: '/participate'
      fullPath: '/api/drawings/$drawingId/participate'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipateRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/participants': {
      id: '/api/drawings/$drawingId/participants'
      path: '/participants'
      fullPath: '/api/drawings/$drawingId/participants'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipantsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/assets': {
      id: '/api/drawings/$drawingId/assets'
      path: '/assets'
      fullPath: '/api/drawings/$drawingId/assets'
      preLoaderRoute: typeof ApiDrawingsDrawingIdAssetsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/$participantId': {
      id: '/api/drawings/$drawingId/$participantId'
      path: '/$participantId'
      fullPath: '/api/drawings/$drawingId/$participantId'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipantIdRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/p/$participantId/comments': {
      id: '/api/drawings/$drawingId/p/$participantId/comments'
      path: '/p/$participantId/comments'
      fullPath: '/api/drawings/$drawingId/p/$participantId/comments'
      preLoaderRoute: typeof ApiDrawingsDrawingIdPParticipantIdCommentsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
  }
}

interface ApiDrawingsDrawingIdRouteChildren {
  ApiDrawingsDrawingIdParticipantIdRoute: typeof ApiDrawingsDrawingIdParticipantIdRoute
  ApiDrawingsDrawingIdAssetsRoute: typeof ApiDrawingsDrawingIdAssetsRoute
  ApiDrawingsDrawingIdParticipantsRoute: typeof ApiDrawingsDrawingIdParticipantsRoute
  ApiDrawingsDrawingIdParticipateRoute: typeof ApiDrawingsDrawingIdParticipateRoute
  ApiDrawingsDrawingIdReserveRoute: typeof ApiDrawingsDrawingIdReserveRoute
  ApiDrawingsDrawingIdSelectWinnersRoute: typeof ApiDrawingsDrawingIdSelectWinnersRoute
  ApiDrawingsDrawingIdSlotsRoute: typeof ApiDrawingsDrawingIdSlotsRoute
  ApiDrawingsDrawingIdStatsRoute: typeof ApiDrawingsDrawingIdStatsRoute
  ApiDrawingsDrawingIdUploadRoute: typeof ApiDrawingsDrawingIdUploadRoute
  ApiDrawingsDrawingIdPParticipantIdCommentsRoute: typeof ApiDrawingsDrawingIdPParticipantIdCommentsRoute
}

const ApiDrawingsDrawingIdRouteChildren: ApiDrawingsDrawingIdRouteChildren = {
  ApiDrawingsDrawingIdParticipantIdRoute:
    ApiDrawingsDrawingIdParticipantIdRoute,
  ApiDrawingsDrawingIdAssetsRoute: ApiDrawingsDrawingIdAssetsRoute,
  ApiDrawingsDrawingIdParticipantsRoute: ApiDrawingsDrawingIdParticipantsRoute,
  ApiDrawingsDrawingIdParticipateRoute: ApiDrawingsDrawingIdParticipateRoute,
  ApiDrawingsDrawingIdReserveRoute: ApiDrawingsDrawingIdReserveRoute,
  ApiDrawingsDrawingIdSelectWinnersRoute:
    ApiDrawingsDrawingIdSelectWinnersRoute,
  ApiDrawingsDrawingIdSlotsRoute: ApiDrawingsDrawingIdSlotsRoute,
  ApiDrawingsDrawingIdStatsRoute: ApiDrawingsDrawingIdStatsRoute,
  ApiDrawingsDrawingIdUploadRoute: ApiDrawingsDrawingIdUploadRoute,
  ApiDrawingsDrawingIdPParticipantIdCommentsRoute:
    ApiDrawingsDrawingIdPParticipantIdCommentsRoute,
}

const ApiDrawingsDrawingIdRouteWithChildren =
  ApiDrawingsDrawingIdRoute._addFileChildren(ApiDrawingsDrawingIdRouteChildren)

interface ApiParticipantParticipantIdRouteChildren {
  ApiParticipantParticipantIdCommentsRoute: typeof ApiParticipantParticipantIdCommentsRoute
}

const ApiParticipantParticipantIdRouteChildren: ApiParticipantParticipantIdRouteChildren =
  {
    ApiParticipantParticipantIdCommentsRoute:
      ApiParticipantParticipantIdCommentsRoute,
  }

const ApiParticipantParticipantIdRouteWithChildren =
  ApiParticipantParticipantIdRoute._addFileChildren(
    ApiParticipantParticipantIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoffeeRoute: CoffeeRoute,
  MercadopagoDemoRoute: MercadopagoDemoRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  ACouponsRoute: ACouponsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationResetPasswordRoute: AuthenticationResetPasswordRoute,
  AuthenticationSignupRoute: AuthenticationSignupRoute,
  DrawingsCreateRoute: DrawingsCreateRoute,
  AccountIndexRoute: AccountIndexRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
  ApiACouponsRoute: ApiACouponsRoute,
  ApiAdsRedeemRoute: ApiAdsRedeemRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCouponsRedeemRoute: ApiCouponsRedeemRoute,
  ApiDrawingsDrawingIdRoute: ApiDrawingsDrawingIdRouteWithChildren,
  ApiDrawingsReservationTimeRoute: ApiDrawingsReservationTimeRoute,
  ApiMercadopagoCreatePreferenceRoute: ApiMercadopagoCreatePreferenceRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
  ApiPacksPurchaseRoute: ApiPacksPurchaseRoute,
  ApiParticipantParticipantIdRoute:
    ApiParticipantParticipantIdRouteWithChildren,
  ApiParticipantsAssetsRoute: ApiParticipantsAssetsRoute,
  ApiParticipantsUploadRoute: ApiParticipantsUploadRoute,
  ApiPaypalCaptureOrderRoute: ApiPaypalCaptureOrderRoute,
  ApiPaypalCreateOrderRoute: ApiPaypalCreateOrderRoute,
  ApiUserBalanceRoute: ApiUserBalanceRoute,
  ApiUserMonthlyAllowanceRoute: ApiUserMonthlyAllowanceRoute,
  ApiWebhookPaypalRoute: ApiWebhookPaypalRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
  DrawingsDrawingIdEditRoute: DrawingsDrawingIdEditRoute,
  SlotDrawingIdNumberToReserveRoute: SlotDrawingIdNumberToReserveRoute,
  ApiDrawingsIndexRoute: ApiDrawingsIndexRoute,
  ApiPacksIndexRoute: ApiPacksIndexRoute,
  DrawingsDrawingIdIndexRoute: DrawingsDrawingIdIndexRoute,
  SlotDrawingIdIndexRoute: SlotDrawingIdIndexRoute,
  DDrawingIdPParticipantRoute: DDrawingIdPParticipantRoute,
  DrawingsDrawingIdMParticipantRoute: DrawingsDrawingIdMParticipantRoute,
  DrawingsDrawingIdPParticipateIdRoute: DrawingsDrawingIdPParticipateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
