/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawingsIndexRouteImport } from './routes/drawings/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as JoinDrawingIdRouteImport } from './routes/join/$drawingId'
import { Route as DrawingsCreateRouteImport } from './routes/drawings/create'
import { Route as DrawingsDrawingIdRouteImport } from './routes/drawings/$drawingId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as AuthenticationSignupRouteImport } from './routes/authentication/signup'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as ApiDrawingsIndexRouteImport } from './routes/api/drawings/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiDrawingsDrawingIdRouteImport } from './routes/api/drawings/$drawingId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiDrawingsDrawingIdParticipateRouteImport } from './routes/api/drawings/$drawingId/participate'
import { Route as ApiDrawingsDrawingIdParticipantsRouteImport } from './routes/api/drawings/$drawingId/participants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/drawings/',
  path: '/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDrawingIdRoute = JoinDrawingIdRouteImport.update({
  id: '/join/$drawingId',
  path: '/join/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsCreateRoute = DrawingsCreateRouteImport.update({
  id: '/drawings/create',
  path: '/drawings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsDrawingIdRoute = DrawingsDrawingIdRouteImport.update({
  id: '/drawings/$drawingId',
  path: '/drawings/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignupRoute = AuthenticationSignupRouteImport.update({
  id: '/authentication/signup',
  path: '/authentication/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsIndexRoute = ApiDrawingsIndexRouteImport.update({
  id: '/api/drawings/',
  path: '/api/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsDrawingIdRoute = ApiDrawingsDrawingIdRouteImport.update({
  id: '/api/drawings/$drawingId',
  path: '/api/drawings/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsDrawingIdParticipateRoute =
  ApiDrawingsDrawingIdParticipateRouteImport.update({
    id: '/participate',
    path: '/participate',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipantsRoute =
  ApiDrawingsDrawingIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/join/$drawingId': typeof JoinDrawingIdRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/join/$drawingId': typeof JoinDrawingIdRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/join/$drawingId': typeof JoinDrawingIdRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/drawings/': typeof ApiDrawingsIndexRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/$drawingId'
    | '/drawings/create'
    | '/join/$drawingId'
    | '/authentication'
    | '/drawings'
    | '/api/auth/$'
    | '/api/drawings/$drawingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/drawings'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/$drawingId'
    | '/drawings/create'
    | '/join/$drawingId'
    | '/authentication'
    | '/drawings'
    | '/api/auth/$'
    | '/api/drawings/$drawingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/drawings'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/$drawingId'
    | '/drawings/create'
    | '/join/$drawingId'
    | '/authentication/'
    | '/drawings/'
    | '/api/auth/$'
    | '/api/drawings/$drawingId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/drawings/'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationSignupRoute: typeof AuthenticationSignupRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DrawingsDrawingIdRoute: typeof DrawingsDrawingIdRoute
  DrawingsCreateRoute: typeof DrawingsCreateRoute
  JoinDrawingIdRoute: typeof JoinDrawingIdRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDrawingsDrawingIdRoute: typeof ApiDrawingsDrawingIdRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiDrawingsIndexRoute: typeof ApiDrawingsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$drawingId': {
      id: '/join/$drawingId'
      path: '/join/$drawingId'
      fullPath: '/join/$drawingId'
      preLoaderRoute: typeof JoinDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/create': {
      id: '/drawings/create'
      path: '/drawings/create'
      fullPath: '/drawings/create'
      preLoaderRoute: typeof DrawingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId': {
      id: '/drawings/$drawingId'
      path: '/drawings/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof DrawingsDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/signup': {
      id: '/authentication/signup'
      path: '/authentication/signup'
      fullPath: '/authentication/signup'
      preLoaderRoute: typeof AuthenticationSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/': {
      id: '/api/drawings/'
      path: '/api/drawings'
      fullPath: '/api/drawings'
      preLoaderRoute: typeof ApiDrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/$drawingId': {
      id: '/api/drawings/$drawingId'
      path: '/api/drawings/$drawingId'
      fullPath: '/api/drawings/$drawingId'
      preLoaderRoute: typeof ApiDrawingsDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/$drawingId/participate': {
      id: '/api/drawings/$drawingId/participate'
      path: '/participate'
      fullPath: '/api/drawings/$drawingId/participate'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipateRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/participants': {
      id: '/api/drawings/$drawingId/participants'
      path: '/participants'
      fullPath: '/api/drawings/$drawingId/participants'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipantsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
  }
}

interface ApiDrawingsDrawingIdRouteChildren {
  ApiDrawingsDrawingIdParticipantsRoute: typeof ApiDrawingsDrawingIdParticipantsRoute
  ApiDrawingsDrawingIdParticipateRoute: typeof ApiDrawingsDrawingIdParticipateRoute
}

const ApiDrawingsDrawingIdRouteChildren: ApiDrawingsDrawingIdRouteChildren = {
  ApiDrawingsDrawingIdParticipantsRoute: ApiDrawingsDrawingIdParticipantsRoute,
  ApiDrawingsDrawingIdParticipateRoute: ApiDrawingsDrawingIdParticipateRoute,
}

const ApiDrawingsDrawingIdRouteWithChildren =
  ApiDrawingsDrawingIdRoute._addFileChildren(ApiDrawingsDrawingIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationSignupRoute: AuthenticationSignupRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DrawingsDrawingIdRoute: DrawingsDrawingIdRoute,
  DrawingsCreateRoute: DrawingsCreateRoute,
  JoinDrawingIdRoute: JoinDrawingIdRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDrawingsDrawingIdRoute: ApiDrawingsDrawingIdRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiDrawingsIndexRoute: ApiDrawingsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
