/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawingsIndexRouteImport } from './routes/drawings/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as DrawingsCreateRouteImport } from './routes/drawings/create'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as AuthenticationSignupRouteImport } from './routes/authentication/signup'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ACouponsRouteImport } from './routes/a/coupons'
import { Route as SlotDrawingIdIndexRouteImport } from './routes/slot/$drawingId/index'
import { Route as DrawingsDrawingIdIndexRouteImport } from './routes/drawings/$drawingId/index'
import { Route as ApiPacksIndexRouteImport } from './routes/api/packs/index'
import { Route as ApiDrawingsIndexRouteImport } from './routes/api/drawings/index'
import { Route as ApiAIndexRouteImport } from './routes/api/a/index'
import { Route as SlotDrawingIdNumberToReserveRouteImport } from './routes/slot/$drawingId/$numberToReserve'
import { Route as DrawingsDrawingIdEditRouteImport } from './routes/drawings/$drawingId/edit'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook.polar'
import { Route as ApiUserMonthlyAllowanceRouteImport } from './routes/api/user/monthly-allowance'
import { Route as ApiUserBalanceRouteImport } from './routes/api/user/balance'
import { Route as ApiParticipantsUploadRouteImport } from './routes/api/participants/upload'
import { Route as ApiParticipantsAssetsRouteImport } from './routes/api/participants/assets'
import { Route as ApiParticipantParticipantIdRouteImport } from './routes/api/participant.$participantId'
import { Route as ApiPacksPurchaseRouteImport } from './routes/api/packs/purchase'
import { Route as ApiDrawingsReservationTimeRouteImport } from './routes/api/drawings/reservation-time'
import { Route as ApiDrawingsDrawingIdRouteImport } from './routes/api/drawings/$drawingId'
import { Route as ApiCouponsRedeemRouteImport } from './routes/api/coupons/redeem'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdsRedeemRouteImport } from './routes/api/ads/redeem'
import { Route as ApiACouponsRouteImport } from './routes/api/a/coupons'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DrawingsDrawingIdPParticipateIdRouteImport } from './routes/drawings/$drawingId/p.$participateId'
import { Route as DrawingsDrawingIdMParticipantRouteImport } from './routes/drawings/$drawingId/m.$participant'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiDrawingsDrawingIdUploadRouteImport } from './routes/api/drawings/$drawingId/upload'
import { Route as ApiDrawingsDrawingIdStatsRouteImport } from './routes/api/drawings/$drawingId.stats'
import { Route as ApiDrawingsDrawingIdSlotsRouteImport } from './routes/api/drawings/$drawingId.slots'
import { Route as ApiDrawingsDrawingIdSelectWinnersRouteImport } from './routes/api/drawings/$drawingId.select-winners'
import { Route as ApiDrawingsDrawingIdReserveRouteImport } from './routes/api/drawings/$drawingId.reserve'
import { Route as ApiDrawingsDrawingIdParticipateRouteImport } from './routes/api/drawings/$drawingId/participate'
import { Route as ApiDrawingsDrawingIdParticipantsRouteImport } from './routes/api/drawings/$drawingId/participants'
import { Route as ApiDrawingsDrawingIdAssetsRouteImport } from './routes/api/drawings/$drawingId/assets'
import { Route as ApiDrawingsDrawingIdParticipantIdRouteImport } from './routes/api/drawings/$drawingId/$participantId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/drawings/',
  path: '/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsCreateRoute = DrawingsCreateRouteImport.update({
  id: '/drawings/create',
  path: '/drawings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSignupRoute = AuthenticationSignupRouteImport.update({
  id: '/authentication/signup',
  path: '/authentication/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ACouponsRoute = ACouponsRouteImport.update({
  id: '/a/coupons',
  path: '/a/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotDrawingIdIndexRoute = SlotDrawingIdIndexRouteImport.update({
  id: '/slot/$drawingId/',
  path: '/slot/$drawingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsDrawingIdIndexRoute = DrawingsDrawingIdIndexRouteImport.update({
  id: '/drawings/$drawingId/',
  path: '/drawings/$drawingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksIndexRoute = ApiPacksIndexRouteImport.update({
  id: '/api/packs/',
  path: '/api/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsIndexRoute = ApiDrawingsIndexRouteImport.update({
  id: '/api/drawings/',
  path: '/api/drawings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAIndexRoute = ApiAIndexRouteImport.update({
  id: '/api/a/',
  path: '/api/a/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotDrawingIdNumberToReserveRoute =
  SlotDrawingIdNumberToReserveRouteImport.update({
    id: '/slot/$drawingId/$numberToReserve',
    path: '/slot/$drawingId/$numberToReserve',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrawingsDrawingIdEditRoute = DrawingsDrawingIdEditRouteImport.update({
  id: '/drawings/$drawingId/edit',
  path: '/drawings/$drawingId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserMonthlyAllowanceRoute = ApiUserMonthlyAllowanceRouteImport.update({
  id: '/api/user/monthly-allowance',
  path: '/api/user/monthly-allowance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserBalanceRoute = ApiUserBalanceRouteImport.update({
  id: '/api/user/balance',
  path: '/api/user/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantsUploadRoute = ApiParticipantsUploadRouteImport.update({
  id: '/api/participants/upload',
  path: '/api/participants/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantsAssetsRoute = ApiParticipantsAssetsRouteImport.update({
  id: '/api/participants/assets',
  path: '/api/participants/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParticipantParticipantIdRoute =
  ApiParticipantParticipantIdRouteImport.update({
    id: '/api/participant/$participantId',
    path: '/api/participant/$participantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPacksPurchaseRoute = ApiPacksPurchaseRouteImport.update({
  id: '/api/packs/purchase',
  path: '/api/packs/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsReservationTimeRoute =
  ApiDrawingsReservationTimeRouteImport.update({
    id: '/api/drawings/reservation-time',
    path: '/api/drawings/reservation-time',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDrawingsDrawingIdRoute = ApiDrawingsDrawingIdRouteImport.update({
  id: '/api/drawings/$drawingId',
  path: '/api/drawings/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsRedeemRoute = ApiCouponsRedeemRouteImport.update({
  id: '/api/coupons/redeem',
  path: '/api/coupons/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsRedeemRoute = ApiAdsRedeemRouteImport.update({
  id: '/api/ads/redeem',
  path: '/api/ads/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiACouponsRoute = ApiACouponsRouteImport.update({
  id: '/api/a/coupons',
  path: '/api/a/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsDrawingIdPParticipateIdRoute =
  DrawingsDrawingIdPParticipateIdRouteImport.update({
    id: '/drawings/$drawingId/p/$participateId',
    path: '/drawings/$drawingId/p/$participateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrawingsDrawingIdMParticipantRoute =
  DrawingsDrawingIdMParticipantRouteImport.update({
    id: '/drawings/$drawingId/m/$participant',
    path: '/drawings/$drawingId/m/$participant',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingsDrawingIdUploadRoute =
  ApiDrawingsDrawingIdUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdStatsRoute =
  ApiDrawingsDrawingIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdSlotsRoute =
  ApiDrawingsDrawingIdSlotsRouteImport.update({
    id: '/slots',
    path: '/slots',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdSelectWinnersRoute =
  ApiDrawingsDrawingIdSelectWinnersRouteImport.update({
    id: '/select-winners',
    path: '/select-winners',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdReserveRoute =
  ApiDrawingsDrawingIdReserveRouteImport.update({
    id: '/reserve',
    path: '/reserve',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipateRoute =
  ApiDrawingsDrawingIdParticipateRouteImport.update({
    id: '/participate',
    path: '/participate',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipantsRoute =
  ApiDrawingsDrawingIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdAssetsRoute =
  ApiDrawingsDrawingIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)
const ApiDrawingsDrawingIdParticipantIdRoute =
  ApiDrawingsDrawingIdParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => ApiDrawingsDrawingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account': typeof AccountIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRoute
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/a': typeof ApiAIndexRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/packs': typeof ApiPacksIndexRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account': typeof AccountIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/drawings': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRoute
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/a': typeof ApiAIndexRoute
  '/api/drawings': typeof ApiDrawingsIndexRoute
  '/api/packs': typeof ApiPacksIndexRoute
  '/drawings/$drawingId': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/a/coupons': typeof ACouponsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/authentication/login': typeof AuthenticationLoginRoute
  '/authentication/signup': typeof AuthenticationSignupRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/drawings/create': typeof DrawingsCreateRoute
  '/account/': typeof AccountIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/api/a/coupons': typeof ApiACouponsRoute
  '/api/ads/redeem': typeof ApiAdsRedeemRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/coupons/redeem': typeof ApiCouponsRedeemRoute
  '/api/drawings/$drawingId': typeof ApiDrawingsDrawingIdRouteWithChildren
  '/api/drawings/reservation-time': typeof ApiDrawingsReservationTimeRoute
  '/api/packs/purchase': typeof ApiPacksPurchaseRoute
  '/api/participant/$participantId': typeof ApiParticipantParticipantIdRoute
  '/api/participants/assets': typeof ApiParticipantsAssetsRoute
  '/api/participants/upload': typeof ApiParticipantsUploadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/monthly-allowance': typeof ApiUserMonthlyAllowanceRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/drawings/$drawingId/edit': typeof DrawingsDrawingIdEditRoute
  '/slot/$drawingId/$numberToReserve': typeof SlotDrawingIdNumberToReserveRoute
  '/api/a/': typeof ApiAIndexRoute
  '/api/drawings/': typeof ApiDrawingsIndexRoute
  '/api/packs/': typeof ApiPacksIndexRoute
  '/drawings/$drawingId/': typeof DrawingsDrawingIdIndexRoute
  '/slot/$drawingId/': typeof SlotDrawingIdIndexRoute
  '/api/drawings/$drawingId/$participantId': typeof ApiDrawingsDrawingIdParticipantIdRoute
  '/api/drawings/$drawingId/assets': typeof ApiDrawingsDrawingIdAssetsRoute
  '/api/drawings/$drawingId/participants': typeof ApiDrawingsDrawingIdParticipantsRoute
  '/api/drawings/$drawingId/participate': typeof ApiDrawingsDrawingIdParticipateRoute
  '/api/drawings/$drawingId/reserve': typeof ApiDrawingsDrawingIdReserveRoute
  '/api/drawings/$drawingId/select-winners': typeof ApiDrawingsDrawingIdSelectWinnersRoute
  '/api/drawings/$drawingId/slots': typeof ApiDrawingsDrawingIdSlotsRoute
  '/api/drawings/$drawingId/stats': typeof ApiDrawingsDrawingIdStatsRoute
  '/api/drawings/$drawingId/upload': typeof ApiDrawingsDrawingIdUploadRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/drawings/$drawingId/m/$participant': typeof DrawingsDrawingIdMParticipantRoute
  '/drawings/$drawingId/p/$participateId': typeof DrawingsDrawingIdPParticipateIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coffee'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/create'
    | '/account'
    | '/authentication'
    | '/drawings'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/polar'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/a'
    | '/api/drawings'
    | '/api/packs'
    | '/drawings/$drawingId'
    | '/slot/$drawingId'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coffee'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/create'
    | '/account'
    | '/authentication'
    | '/drawings'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/polar'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/a'
    | '/api/drawings'
    | '/api/packs'
    | '/drawings/$drawingId'
    | '/slot/$drawingId'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/coffee'
    | '/store'
    | '/support'
    | '/a/coupons'
    | '/api/checkout'
    | '/authentication/login'
    | '/authentication/signup'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/drawings/create'
    | '/account/'
    | '/authentication/'
    | '/drawings/'
    | '/api/a/coupons'
    | '/api/ads/redeem'
    | '/api/auth/$'
    | '/api/coupons/redeem'
    | '/api/drawings/$drawingId'
    | '/api/drawings/reservation-time'
    | '/api/packs/purchase'
    | '/api/participant/$participantId'
    | '/api/participants/assets'
    | '/api/participants/upload'
    | '/api/user/balance'
    | '/api/user/monthly-allowance'
    | '/api/webhook/polar'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/drawings/$drawingId/edit'
    | '/slot/$drawingId/$numberToReserve'
    | '/api/a/'
    | '/api/drawings/'
    | '/api/packs/'
    | '/drawings/$drawingId/'
    | '/slot/$drawingId/'
    | '/api/drawings/$drawingId/$participantId'
    | '/api/drawings/$drawingId/assets'
    | '/api/drawings/$drawingId/participants'
    | '/api/drawings/$drawingId/participate'
    | '/api/drawings/$drawingId/reserve'
    | '/api/drawings/$drawingId/select-winners'
    | '/api/drawings/$drawingId/slots'
    | '/api/drawings/$drawingId/stats'
    | '/api/drawings/$drawingId/upload'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/drawings/$drawingId/m/$participant'
    | '/drawings/$drawingId/p/$participateId'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoffeeRoute: typeof CoffeeRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  ACouponsRoute: typeof ACouponsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationSignupRoute: typeof AuthenticationSignupRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DrawingsCreateRoute: typeof DrawingsCreateRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
  ApiACouponsRoute: typeof ApiACouponsRoute
  ApiAdsRedeemRoute: typeof ApiAdsRedeemRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCouponsRedeemRoute: typeof ApiCouponsRedeemRoute
  ApiDrawingsDrawingIdRoute: typeof ApiDrawingsDrawingIdRouteWithChildren
  ApiDrawingsReservationTimeRoute: typeof ApiDrawingsReservationTimeRoute
  ApiPacksPurchaseRoute: typeof ApiPacksPurchaseRoute
  ApiParticipantParticipantIdRoute: typeof ApiParticipantParticipantIdRoute
  ApiParticipantsAssetsRoute: typeof ApiParticipantsAssetsRoute
  ApiParticipantsUploadRoute: typeof ApiParticipantsUploadRoute
  ApiUserBalanceRoute: typeof ApiUserBalanceRoute
  ApiUserMonthlyAllowanceRoute: typeof ApiUserMonthlyAllowanceRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DrawingsDrawingIdEditRoute: typeof DrawingsDrawingIdEditRoute
  SlotDrawingIdNumberToReserveRoute: typeof SlotDrawingIdNumberToReserveRoute
  ApiAIndexRoute: typeof ApiAIndexRoute
  ApiDrawingsIndexRoute: typeof ApiDrawingsIndexRoute
  ApiPacksIndexRoute: typeof ApiPacksIndexRoute
  DrawingsDrawingIdIndexRoute: typeof DrawingsDrawingIdIndexRoute
  SlotDrawingIdIndexRoute: typeof SlotDrawingIdIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DrawingsDrawingIdMParticipantRoute: typeof DrawingsDrawingIdMParticipantRoute
  DrawingsDrawingIdPParticipateIdRoute: typeof DrawingsDrawingIdPParticipateIdRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/create': {
      id: '/drawings/create'
      path: '/drawings/create'
      fullPath: '/drawings/create'
      preLoaderRoute: typeof DrawingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/signup': {
      id: '/authentication/signup'
      path: '/authentication/signup'
      fullPath: '/authentication/signup'
      preLoaderRoute: typeof AuthenticationSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/coupons': {
      id: '/a/coupons'
      path: '/a/coupons'
      fullPath: '/a/coupons'
      preLoaderRoute: typeof ACouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$drawingId/': {
      id: '/slot/$drawingId/'
      path: '/slot/$drawingId'
      fullPath: '/slot/$drawingId'
      preLoaderRoute: typeof SlotDrawingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/': {
      id: '/drawings/$drawingId/'
      path: '/drawings/$drawingId'
      fullPath: '/drawings/$drawingId'
      preLoaderRoute: typeof DrawingsDrawingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/': {
      id: '/api/packs/'
      path: '/api/packs'
      fullPath: '/api/packs'
      preLoaderRoute: typeof ApiPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/': {
      id: '/api/drawings/'
      path: '/api/drawings'
      fullPath: '/api/drawings'
      preLoaderRoute: typeof ApiDrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a/': {
      id: '/api/a/'
      path: '/api/a'
      fullPath: '/api/a'
      preLoaderRoute: typeof ApiAIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$drawingId/$numberToReserve': {
      id: '/slot/$drawingId/$numberToReserve'
      path: '/slot/$drawingId/$numberToReserve'
      fullPath: '/slot/$drawingId/$numberToReserve'
      preLoaderRoute: typeof SlotDrawingIdNumberToReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/edit': {
      id: '/drawings/$drawingId/edit'
      path: '/drawings/$drawingId/edit'
      fullPath: '/drawings/$drawingId/edit'
      preLoaderRoute: typeof DrawingsDrawingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/monthly-allowance': {
      id: '/api/user/monthly-allowance'
      path: '/api/user/monthly-allowance'
      fullPath: '/api/user/monthly-allowance'
      preLoaderRoute: typeof ApiUserMonthlyAllowanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/balance': {
      id: '/api/user/balance'
      path: '/api/user/balance'
      fullPath: '/api/user/balance'
      preLoaderRoute: typeof ApiUserBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participants/upload': {
      id: '/api/participants/upload'
      path: '/api/participants/upload'
      fullPath: '/api/participants/upload'
      preLoaderRoute: typeof ApiParticipantsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participants/assets': {
      id: '/api/participants/assets'
      path: '/api/participants/assets'
      fullPath: '/api/participants/assets'
      preLoaderRoute: typeof ApiParticipantsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/participant/$participantId': {
      id: '/api/participant/$participantId'
      path: '/api/participant/$participantId'
      fullPath: '/api/participant/$participantId'
      preLoaderRoute: typeof ApiParticipantParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/purchase': {
      id: '/api/packs/purchase'
      path: '/api/packs/purchase'
      fullPath: '/api/packs/purchase'
      preLoaderRoute: typeof ApiPacksPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/reservation-time': {
      id: '/api/drawings/reservation-time'
      path: '/api/drawings/reservation-time'
      fullPath: '/api/drawings/reservation-time'
      preLoaderRoute: typeof ApiDrawingsReservationTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/$drawingId': {
      id: '/api/drawings/$drawingId'
      path: '/api/drawings/$drawingId'
      fullPath: '/api/drawings/$drawingId'
      preLoaderRoute: typeof ApiDrawingsDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/redeem': {
      id: '/api/coupons/redeem'
      path: '/api/coupons/redeem'
      fullPath: '/api/coupons/redeem'
      preLoaderRoute: typeof ApiCouponsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/redeem': {
      id: '/api/ads/redeem'
      path: '/api/ads/redeem'
      fullPath: '/api/ads/redeem'
      preLoaderRoute: typeof ApiAdsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a/coupons': {
      id: '/api/a/coupons'
      path: '/api/a/coupons'
      fullPath: '/api/a/coupons'
      preLoaderRoute: typeof ApiACouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/p/$participateId': {
      id: '/drawings/$drawingId/p/$participateId'
      path: '/drawings/$drawingId/p/$participateId'
      fullPath: '/drawings/$drawingId/p/$participateId'
      preLoaderRoute: typeof DrawingsDrawingIdPParticipateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/$drawingId/m/$participant': {
      id: '/drawings/$drawingId/m/$participant'
      path: '/drawings/$drawingId/m/$participant'
      fullPath: '/drawings/$drawingId/m/$participant'
      preLoaderRoute: typeof DrawingsDrawingIdMParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawings/$drawingId/upload': {
      id: '/api/drawings/$drawingId/upload'
      path: '/upload'
      fullPath: '/api/drawings/$drawingId/upload'
      preLoaderRoute: typeof ApiDrawingsDrawingIdUploadRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/stats': {
      id: '/api/drawings/$drawingId/stats'
      path: '/stats'
      fullPath: '/api/drawings/$drawingId/stats'
      preLoaderRoute: typeof ApiDrawingsDrawingIdStatsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/slots': {
      id: '/api/drawings/$drawingId/slots'
      path: '/slots'
      fullPath: '/api/drawings/$drawingId/slots'
      preLoaderRoute: typeof ApiDrawingsDrawingIdSlotsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/select-winners': {
      id: '/api/drawings/$drawingId/select-winners'
      path: '/select-winners'
      fullPath: '/api/drawings/$drawingId/select-winners'
      preLoaderRoute: typeof ApiDrawingsDrawingIdSelectWinnersRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/reserve': {
      id: '/api/drawings/$drawingId/reserve'
      path: '/reserve'
      fullPath: '/api/drawings/$drawingId/reserve'
      preLoaderRoute: typeof ApiDrawingsDrawingIdReserveRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/participate': {
      id: '/api/drawings/$drawingId/participate'
      path: '/participate'
      fullPath: '/api/drawings/$drawingId/participate'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipateRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/participants': {
      id: '/api/drawings/$drawingId/participants'
      path: '/participants'
      fullPath: '/api/drawings/$drawingId/participants'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipantsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/assets': {
      id: '/api/drawings/$drawingId/assets'
      path: '/assets'
      fullPath: '/api/drawings/$drawingId/assets'
      preLoaderRoute: typeof ApiDrawingsDrawingIdAssetsRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
    '/api/drawings/$drawingId/$participantId': {
      id: '/api/drawings/$drawingId/$participantId'
      path: '/$participantId'
      fullPath: '/api/drawings/$drawingId/$participantId'
      preLoaderRoute: typeof ApiDrawingsDrawingIdParticipantIdRouteImport
      parentRoute: typeof ApiDrawingsDrawingIdRoute
    }
  }
}

interface ApiDrawingsDrawingIdRouteChildren {
  ApiDrawingsDrawingIdParticipantIdRoute: typeof ApiDrawingsDrawingIdParticipantIdRoute
  ApiDrawingsDrawingIdAssetsRoute: typeof ApiDrawingsDrawingIdAssetsRoute
  ApiDrawingsDrawingIdParticipantsRoute: typeof ApiDrawingsDrawingIdParticipantsRoute
  ApiDrawingsDrawingIdParticipateRoute: typeof ApiDrawingsDrawingIdParticipateRoute
  ApiDrawingsDrawingIdReserveRoute: typeof ApiDrawingsDrawingIdReserveRoute
  ApiDrawingsDrawingIdSelectWinnersRoute: typeof ApiDrawingsDrawingIdSelectWinnersRoute
  ApiDrawingsDrawingIdSlotsRoute: typeof ApiDrawingsDrawingIdSlotsRoute
  ApiDrawingsDrawingIdStatsRoute: typeof ApiDrawingsDrawingIdStatsRoute
  ApiDrawingsDrawingIdUploadRoute: typeof ApiDrawingsDrawingIdUploadRoute
}

const ApiDrawingsDrawingIdRouteChildren: ApiDrawingsDrawingIdRouteChildren = {
  ApiDrawingsDrawingIdParticipantIdRoute:
    ApiDrawingsDrawingIdParticipantIdRoute,
  ApiDrawingsDrawingIdAssetsRoute: ApiDrawingsDrawingIdAssetsRoute,
  ApiDrawingsDrawingIdParticipantsRoute: ApiDrawingsDrawingIdParticipantsRoute,
  ApiDrawingsDrawingIdParticipateRoute: ApiDrawingsDrawingIdParticipateRoute,
  ApiDrawingsDrawingIdReserveRoute: ApiDrawingsDrawingIdReserveRoute,
  ApiDrawingsDrawingIdSelectWinnersRoute:
    ApiDrawingsDrawingIdSelectWinnersRoute,
  ApiDrawingsDrawingIdSlotsRoute: ApiDrawingsDrawingIdSlotsRoute,
  ApiDrawingsDrawingIdStatsRoute: ApiDrawingsDrawingIdStatsRoute,
  ApiDrawingsDrawingIdUploadRoute: ApiDrawingsDrawingIdUploadRoute,
}

const ApiDrawingsDrawingIdRouteWithChildren =
  ApiDrawingsDrawingIdRoute._addFileChildren(ApiDrawingsDrawingIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoffeeRoute: CoffeeRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  ACouponsRoute: ACouponsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationSignupRoute: AuthenticationSignupRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DrawingsCreateRoute: DrawingsCreateRoute,
  AccountIndexRoute: AccountIndexRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
  ApiACouponsRoute: ApiACouponsRoute,
  ApiAdsRedeemRoute: ApiAdsRedeemRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCouponsRedeemRoute: ApiCouponsRedeemRoute,
  ApiDrawingsDrawingIdRoute: ApiDrawingsDrawingIdRouteWithChildren,
  ApiDrawingsReservationTimeRoute: ApiDrawingsReservationTimeRoute,
  ApiPacksPurchaseRoute: ApiPacksPurchaseRoute,
  ApiParticipantParticipantIdRoute: ApiParticipantParticipantIdRoute,
  ApiParticipantsAssetsRoute: ApiParticipantsAssetsRoute,
  ApiParticipantsUploadRoute: ApiParticipantsUploadRoute,
  ApiUserBalanceRoute: ApiUserBalanceRoute,
  ApiUserMonthlyAllowanceRoute: ApiUserMonthlyAllowanceRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DrawingsDrawingIdEditRoute: DrawingsDrawingIdEditRoute,
  SlotDrawingIdNumberToReserveRoute: SlotDrawingIdNumberToReserveRoute,
  ApiAIndexRoute: ApiAIndexRoute,
  ApiDrawingsIndexRoute: ApiDrawingsIndexRoute,
  ApiPacksIndexRoute: ApiPacksIndexRoute,
  DrawingsDrawingIdIndexRoute: DrawingsDrawingIdIndexRoute,
  SlotDrawingIdIndexRoute: SlotDrawingIdIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DrawingsDrawingIdMParticipantRoute: DrawingsDrawingIdMParticipantRoute,
  DrawingsDrawingIdPParticipateIdRoute: DrawingsDrawingIdPParticipateIdRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
